[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = ["@openzeppelin07/=lib/openzeppelin-contracts-07/","@openzeppelin/=lib/openzeppelin-contracts/","@uniswap/v3-core/=lib/v3-core/","@uniswap/v3-periphery/=lib/v3-periphery/","@uniswap/v2-core/=lib/v2-core","@uniswap/v2-periphery/=lib/v2-periphery","@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts"]
solc-version = "0.8.19"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config